
POST http://localhost:3001/api/shorturl HTTP/1.1
Content-Type: application/json

{
  "fullUrl":"www.youtube.com"
}


###

POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "username":"yusuf",
  "password":"test"
}

###

POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "username":"yusuf",
  "password":"test"
}
